### ISSUE TITLE
Exports of this package seem to be wrong.

### ISSUE THREAD

**Issue by LinusBorg** [encyjs/ency#7]
## The Problem

`src/index.js` currently does this:
```javascript
import initTask from './task/index'
import createTask from './task/index'
// ...

export default createTask

export {
  initTask,
  // ...
}

```
Both import the same function - the default export of `./src/tsk/index.js`. 

## Solution
I *think* Line 2 of `index.js` should be
```javascript
import { createTask } from './task/index'
```

Resulting Problem:

The result is that the following code does not create a task runner, it returns `createTask`
```javascript
import task from 'ency'

const runner = task(someFunction)
```

## Workaround
```javscript
import initTask from 'ency'

const task = initTask({})

const runner = task(someFunction)
```

**Comment by alidcastano** [comment]
The import duplication is a silly mistake on my part, thanks for bringing it to my attention.

I changed the default export to `initTask` so that users using `Ency` for js libraries, such as I did for `vuency`, can pass additional modifiers to the task factory.

```
import { initTask } from 'ency'
const createTask = initTask(additionalModifiers)
```
Here's a full snippet from Vuency codebase: https://github.com/encyjs/vuency/blob/master/src/mixin.js#L9

However, I think it'll be best to make the default export `createTask`, for users using Ency alone, but also export `initTask` for libraries. 

Your PR should fix this. I'd have to double check but the work around should be needed once the import is corrected.

You can import and use both options: `import createTask, { initTask } from 'Ency'`

**Comment by alidcastano** [comment]
@LinusBorg I'm curious were you just experimenting with Ency? I feel like using it via the Vue plugin would be preferable.

**Comment by LinusBorg** [comment]
I'm trying to write a HoF for vuex actions to implement `takeLast` (which would be 'restart' in ency terms i guess) etc, so Vuency doesn't work for that, obviously.

Ency actually does that quite nicely as far as my experiments go, so good job. :)

Though I came across the fact that I can't reall cancel the *currently yielded* prmoise, only the next...
```javascript
function * myAction({commit}, payload) {
  const result = yield requesSomeDataViaAjax() // when i call `cancel()` while this is already running, cancellation wont happen

  yield // so this serves as a kind of breakpoint at which `caccel()` can stop before the commit.
  commit('MY_MUTAION', data)
}
```

Is that expected?

Anyway, will share the repository with you when I have uploaded it to github. No idea if I still wiht ency or try to re-implement a couple ideas from it for size.

**Comment by alidcastano** [comment]
Yeah, it should definitely be canceling in that first yield so either 1) the yield finished before the cancellation or 2) there's a bug 😅. 

Have you experimented with increasing the time span of the call to see if it's the latter? 

Also, for context, this is basically a framework-independent implementation of [ember-concurrency](https://github.com/machty/ember-concurrency). I believe they have a keepLatest option (http://ember-concurrency.com/#/docs/task-concurrency), which I have an issue open for since I've  been meaning to implement it. Let me know if that's what you're looking for.

Anyways, I created this so that it could be used with other libraries so if there's anyway I could refactor the code to make it more useful for lighter implementations, I'd definitely consider it. Though I understand if you'd prefer to make a minimal independent solution for Vuex.
